---
abstract: 'A suit of XML tools with Antlers.'
author:
  - 'Chris Prather <chris@prather.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Path::Class: 0
  Test::Deep: 0
  Test::Exception: 0
  Test::More: 0
  Test::Simple: 0.94
  Test::XML: 0.00
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300013, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Toolkit
requires:
  Bread::Board: 0
  Bread::Board::Container: 0
  Devel::PackagePath: 0.01
  Encode: 0
  Moose: 0.92
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Aliases: 0
  MooseX::App::Cmd: 0
  MooseX::App::Cmd::Command: 0
  MooseX::Getopt::Dashes: 0
  MooseX::MetaDescription: 0.03
  MooseX::MetaDescription::Description: 0
  MooseX::MetaDescription::Meta::Attribute: 0
  MooseX::MetaDescription::Meta::Trait: 0
  MooseX::NonMoose: 0
  MooseX::Types::Path::Class: 0.04
  Template: 2.20
  XML::SAX: 0.96
  XML::SAX::Base: 0
  XML::SAX::Writer: 0.50
  aliased: 0
  namespace::autoclean: 0
  strict: 0
  warnings: 0
version: 0.15
