---
abstract: 'A set of tools for dealing with XML with the Way of the Moose.'
author:
  - 'Chris Prather  C<< <chris@prather.org> >>'
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Toolkit
no_index:
  directory:
    - ex
    - inc
    - t
requires:
  Encode: 2.26
  Moose: 0.60
  Moose::Autobox: 0.08
  MooseX::AttributeHelpers: 0.13
  MooseX::MetaDescription: 0.03
  MooseX::Types::Path::Class: 0.04
  Template: 2.20
  XML::SAX: 0.96
  XML::SAX::Writer: 0.50
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
